### PR TITLE
Fix installing error due to PyYaml version

### LINKED ISSUE #122: Deprecated config in `setup.cfg`
When installing this package in a conda env with python=3.8:

```
Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      /private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      Traceback (most recent call last):
        File "/Users/chiararasi/miniconda3/envs/loqus/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/chiararasi/miniconda3/envs/loqus/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/chiararasi/miniconda3/envs/loqus/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 318, in run
          self.find_sources()
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
          mm.run()
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 548, in run
          self.add_defaults()
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 586, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
          super().add_defaults()
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/private/var/folders/9x/2v5jk6391t3dbdsr7kpnl4t80000gp/T/pip-build-env-pnr_08xc/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
```

### PR DESCRIPTION
**Pull request by northwestwitch**
### This PR adds | fixes:
- Fix #122 

Check also the issue on the PyYAML repo: https://github.com/yaml/pyyaml/issues/724

### How to test:
- Run pip install -e . from main branch and this branch

### Expected outcome:
- [x] The repo should install using this branch

### Review:
- [ ] Code approved by
- [x] Tests executed by CR

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by northwestwitch** [comment]
Master branch: 🚫 

image


This branch: 🆗 

image

**Comment by dnil** [comment]
The change looks good to me, and passes tests. Did you try something a bit yaml related specifically while testing? I suppose there are configs to read and what not?

In general, it looks like this package has inordinately many frozen dependency versions. I can understand cyvcf2 perhaps, but... 😆

**Comment by northwestwitch** [comment]
> In general, it looks like this package has inordinately many frozen dependency versions. I can understand cyvcf2 perhaps, but... 😆

Yeah, I agree

**Review by dnil — APPROVED** [review]

**Comment by dnil** [comment]
And I forgot to hit "approve"... Time for some food. 😆

**Comment by northwestwitch** [comment]
That's weird, I don't find anywhere in the code where PyYaml is used..

> The change looks good to me, and passes tests. Did you try something a bit yaml related specifically while testing? I suppose there are configs to read and what not?

Tested with a simple config file to connect to my local db:

yaml file content:
image


image

**Comment by dnil** [comment]
Here, I think, so testing config was a good call. 👍 
https://github.com/Clinical-Genomics/loqusdb/blob/f9c24c2d3f228207affd3e346fd62f962a704774/loqusdb/commands/cli.py#L5

**Pull request merged**
